# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: beagle
description: Beagle is an open source framework for multiplatform development using the concept of Server-Driven UI.
version: 0.9.4-alpha
homepage: https://github.com/ZupIT/beagle-flutter/tree/main/beagle

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.5.0+3
  get_it: ^7.2.0
  http: ^0.13.3
  meta: ^1.7.0
  url_launcher: ^6.0.9
  yoga_engine: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  mocktail: ^0.1.4

flutter:
  plugin:
    platforms:
      android:
        package: br.com.zup.beagle.beagle
        pluginClass: BeaglePlugin
      ios:
        pluginClass: BeaglePlugin

  assets:
    - assets/js/beagle.js
