name: Beagle Flutter Pull Request

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: subosito/flutter-action@v1
                with:
                  channel: 'stable' # or: 'dev' or 'beta'
                  flutter-version: '2.5.1'
            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            -   name: Cache pub dependences
                uses: actions/cache@v2
                env:
                    pub-cache-key: pub-cache
                    pub-path: ~/.pub-cache
                with:
                    path: ${{ env.pub-path }}
                    key: ${{ runner.os }}-build-${{ env.pub-cache-key }}
                    restore-keys: ${{ runner.os }}-build-${{ env.pub-cache-key }}
            -   name: Run pr check
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: bundle exec fastlane flutter pull_request_verification
