name: Horusec Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  horusec:
    name: horusec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
          
      - name: Running Horusec
        env:
          HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p . -e true -u "https://api-horusec.zup.com.br" -G true -n "${GITHUB_REPOSITORY}_${GITHUB_REF##*/}"
